imports:
    - ../config/config.yml

environment: development

directories:
    src: ../src
    public: ./
    cache: ../cache
    template: ../src/template

engines:
    minifier: false

cache:
    images: true
